#!/bin/bash

echo "🔧 Reset MySQL Root Password"
echo "============================="
echo ""
echo "Jalankan command ini satu per satu:"
echo ""
echo "1. Stop MySQL:"
echo "   brew services stop mysql"
echo ""
echo "2. Start MySQL dalam safe mode (jalankan di background):"
echo "   mysqld_safe --skip-grant-tables &"
echo ""
echo "3. Tunggu 5 detik, lalu login tanpa password:"
echo "   mysql -uroot"
echo ""
echo "4. Di MySQL prompt, jalankan:"
echo "   FLUSH PRIVILEGES;"
echo "   ALTER USER 'root'@'localhost' IDENTIFIED BY 'bintang123';"
echo "   FLUSH PRIVILEGES;"
echo "   EXIT;"
echo ""
echo "5. Kill proses MySQL safe mode:"
echo "   killall mysqld"
echo ""
echo "6. Start MySQL normal:"
echo "   brew services start mysql"
echo ""
echo "7. Login dengan password baru:"
echo "   mysql -uroot -p123123"
echo ""
echo "8. Buat database ecommerce:"
echo "   CREATE DATABASE ecommerce;"
echo "   EXIT;"
echo ""
echo "============================="
echo "Atau lebih gampang: PAKAI DBEAVER!"
echo ""
echo "DBeaver bisa connect ke MySQL yang lagi jalan tanpa perlu tahu password root."
echo "Cek connection yang udah ada di DBeaver, pasti ada yang bisa connect."
